### PR TITLE
Features in Apple landing page

### PR DESCRIPTION
**Pull request by Eder-PG**
First submission for the 4th project

No errors on Stickler or on the HTML validator

Any feedback is welcome

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @Eder-PG  , 👋 You have done a great job in this project 👏 

* [x] background image and main text are misaligned, fix that

image



----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by Eder-PG** [comment]
Fixed overlapping text by adding a min-height attribute to the article section when using screens under 720p in total height

Thanks for the catch!

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi @Eder-PG , Great job, however,
1. > This section of the page is not properly spaced:
- **Yours:**
image
- **Original:**
image

2. > The background image in this section is not properly aligned and the boxes are not properly sized:
- **Yours:**
image

- **Original:**
image

3. > Add a live link to your README.

**Great job so far. Please make these adjustments and you will be good to :airplane:**

### Status: Changes required.

**Comment by Eder-PG** [comment]
Implemented fixes on previously stated issues

-increased minimum size of the article container to show more room beneath the title
-added a margin for the promotions on the aside
-changed orientation for the backgrounds on the aside and added minimum height to avoid cutting
-added a live link on the readme file (it only shows the main branch which is empty right now)

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Great job making the requested changes, but you have one issue to take care of now:
> Your nav bar is not properly positioned anymore:
image
**Please adjust this and make another code review request. You are almost there. :+1:**

**Comment by Eder-PG** [comment]
Added a minimum height size for the whole page to avoid any other overlapping of the elements

**Review by mosesogwo — APPROVED** [review]
### :trophy: Congratulations! You have done a good job.
You may now merge to master.

### Status: Approved!

**Pull request merged**
